version: 2
jobs:
  build:
    working_directory: ./tmp
    docker:
      - image: node:8.0
    steps:
      - checkout
      - run:
        name: "Checking versions"
        command: |
          node -v
          npm -v